blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(
        r'^$',
        'blog.views.index',
        name = 'index'),
    url(
        r'^post/(?P<pk>[0-9]+)/$', 
        'blog.views.view_post', 
        name='post'),
    url(
        r'^category/(?P<pk>[0-9]+)/$', 
        'blog.views.view_category', 
        name='category'),
    
]

mysite/urls.py
from django.conf.urls import include, url
import settings
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/rango/'

urlpatterns = [
    url(r'^500/$', TemplateView.as_view(template_name="404.html")),
    url(r'^404/$', TemplateView.as_view(template_name="404.html")),
    url(r'^$', 'users.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace="users")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^rango/', include('rango.urls', namespace="rango")),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATIC_DIR}),
]

urlpatterns += staticfiles_urlpatterns()

rango/urls.py
from django.conf.urls import url
from . import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^like_category/$', views.like_category, name='like_category'),
    url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category')
]

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

rango/forms.py
from django import forms
from rango.models import Page, Category

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

rango/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    most_viewed_pages = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'most_viewed_pages': most_viewed_pages}

    visits = int(request.COOKIES.get('visits', '1'))

    reset_last_visit_time = False
    response = render(request, 'rango/index.html', context_dict)
    # Does the cookie last_visit exist?
    if 'last_visit' in request.COOKIES:
    
        last_visit = request.COOKIES['last_visit']        
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        if (datetime.now() - last_visit_time).days > 0:
            visits = visits + 1
            reset_last_visit_time = True
    else:
        
        reset_last_visit_time = True
        context_dict['visits'] = visits
        response = render(request, 'rango/index.html', context_dict)

    if reset_last_visit_time:
        response.set_cookie('last_visit', datetime.now())
        response.set_cookie('visits', visits)

    return response


def about(request):
    if request.COOKIES.get('visits'):
        count = request.COOKIES.get('visits', '1')
    else:
        count = 0

    return render(request, 'rango/about.html', {'visits': count})


def category(request, category_name_slug):

    # Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
        context_dict['category_name_slug'] = category_name_slug
        category.views = category.views + 1
        category.save()
    except Category.DoesNotExist:
        pass

    return render(request, 'rango/category.html', context_dict)


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return index(request)
        else:
            print form.errors
    else:
        form = CategoryForm()

    return render(request, 'rango/add_category.html', {'form': form})
 

def add_page(request, category_name_slug):

    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
                cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                # probably better to use a redirect here.
                return category(request, category_name_slug)
        else:
            print form.errors
    else:
        form = PageForm()

    context_dict = {'form':form, 'category': cat, 'category_name_slug': category_name_slug}

    return render(request, 'rango/add_page.html', context_dict)


def track_url(request):
    context = RequestContext(request)
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        print(request.GET)
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views = page.views + 1
                page.save()
                url = page.url
            except:
                pass

    return redirect(url)


@login_required
def like_category(request):

    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']

    likes = 0
    if cat_id:
        cat = Category.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes + 1
            cat.likes =  likes
            cat.save()

    return HttpResponse(likes)


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results > 0:
        if len(cat_list) > max_results:
                cat_list = cat_list[:max_results]
    return cat_list


def suggest_category(request):
    cat_list = []
    starts_with = ''
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)

    return render(request, 'rango/cats.html', {'cats': cat_list })

rango/templates/rango/about.html
{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>About</h1>
    </div>
    <div>
        <p></strong>.</p>
        <a href="/rango/">Index</a>
        <h5>You visited this page {{visits}} times</h5>
        <img  width="90" height="100" src="{% static "images/rango.jpg" %}" alt="Picture of Rango" /> 
    </div>
    <div id="msg">Hello</div>
{% endblock %}

rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title %} {{ category_name }} {% endblock %}

{% block body_block %}

    <form role="form"  id="category_form" method="post" action="/rango/add_category/">
        <h2 class="form-signin-heading">Add a Category <a href="/rango/category/{{category.slug}}/"> {{ category.name }}</a></h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
            {% endfor %}

        <br/>
        <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
    </form>
{% endblock %}

rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Add Page{% endblock %}

{% block body_block %}
    {% if category %}

        <form role="form"  id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
            <h2 class="form-signin-heading">Add a Page to <a href="/rango/category/{{category.slug}}/"> {{ category.name }}</a></h2>
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}<br/>
                        {{ field }}<br/>
                    {% endfor %}

                <br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
        </form>
    {%  else %}
            <p>This is category does not exist.</p>
    {%  endif %}

{% endblock %}

rango/templates/rango/base.html
{% load rango_extras %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static "js/rango-jquery.js" %}"></script>
    <script src="{% static "js/rango-ajax.js" %}"></script>

  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/rango/">Shadownet</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                        <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>

              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-list">
                <li class="nav-header">Find a Category</li>
                <form>
                <label></label>
                <li><input  class="search-query span10" type="text" name="suggestion" value="" id="suggestion" /></li>
                </form>
            </ul>
            <div id="cats">
            </div>

            {% block side_block %}
            {% get_category_list category%}
            {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
                </div>
        </div>
      </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

rango/templates/rango/category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <h1>{{ category_name }}</h1>
    {% if category %}
        {% if pages %}
        <ul>
            {% for page in pages %}
                <li>
                    <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
                    {% if page.views > 1 %}
                        ({{ page.views }} views)
                        {% elif page.views == 1 %}
                        ({{ page.views }} view)
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="/rango/category/{{category.slug}}/add_page/">Add a Page</a>
        {% endif %}

        <p>
            <strong id="like_count">{{ category.likes }}</strong> people like this category

            {% if user.is_authenticated %}
                <button id="likes" data-catid="{{category.id}}" class="btn btn-primary" type="button">
                <span class="glyphicon glyphicon-thumbs-up"></span>
                Like
                </button>
            {% endif %}
        </p>


    {% else %}
        The specified category {{ category_name }} does not exist!
    {% endif %}
{% endblock %}

rango/templates/rango/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
        {% if c == act_cat %}
             <li  class="active" >
        {% else  %}
             <li>
        {% endif %}
            <a href="{% url 'rango:category'  c.slug %}">{{ c.name }}</a></li>
    {% endfor %}

{% else %}
    <li> <strong >There are no category present.</strong></li>

    </ul>
{% endif %}

rango/templates/rango/index.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Index{% endblock %}

{% block body_block %}
{% if user.is_authenticated %}
    <div class="page-header">
        <h4>Welcome, {{ user.username }}!</h4>
        {% else %}
            <h1>Rango says... hello world!</h1>
        {% endif %}
    </div>

    <div class="row placeholders">
    <div class="col-xs-12 col-sm-6 placeholder">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Categories</h3>
            </div>
        </div>

        {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item"><a href="{% url 'rango:category'  category.slug %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    </div>

    <div class="col-xs-12 col-sm-6 placeholder">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Most viewed pages</h3>
            </div>
        </div>

        {% if most_viewed_pages %}
            <ul class="list-group">
                {% for page in most_viewed_pages %}
                 <li class="list-group-item"><a href="{{page.url}}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    </div>

    </div>

{% endblock %}