blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(
        r'^$',
        'blog.views.index',
        name = 'index'),
    url(
        r'^post/(?P<pk>[0-9]+)/$', 
        'blog.views.view_post', 
        name='post'),
    url(
        r'^category/(?P<pk>[0-9]+)/$', 
        'blog.views.view_category', 
        name='category'),
    
]

mysite/urls.py
from django.conf.urls import include, url
import settings
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/rango/'

urlpatterns = [
    url(r'^500/$', TemplateView.as_view(template_name="404.html")),
    url(r'^404/$', TemplateView.as_view(template_name="404.html")),
    url(r'^$', 'users.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace="users")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^rango/', include('rango.urls', namespace="rango")),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATIC_DIR}),
]

urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=100, db_index=True)

    def __unicode__(self):
        return '%s' % self.title


class Blog(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    posted = models.DateField(db_index=True, auto_now_add=True)
    category = models.ForeignKey('Category')

    def __unicode__(self):
        return '%s' % self.title

blog/views.py
from django.shortcuts import render_to_response, get_object_or_404
from blog.models import Blog, Category

# Create your views here.

def index(request):
    return render_to_response('blog/index.html', {
        'categories': Category.objects.all(),
        'posts': Blog.objects.all()[:5]
    })

def view_post(request, pk):
    return render_to_response('blog/view_post.html', {
        'post': get_object_or_404(Blog, pk=pk)
    })

def view_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render_to_response('blog/view_category.html',{
        'category' : category,
        'posts' : Blog.objects.filter(category=category)[:5]
    })

blog/templates/blog/base.html
<html>
    <head>
        <title>{% block head_title %}Welcome to my blog{% endblock %}</title>
    </head>
    <body>
        <h1>{% block title %}Welcome to my block{% endblock %}</h1>
        {% block content %}

        {% endblock %}
    </body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}Welcome to my blog{% endblock %}

{% block content %}
    <h2>Categories</h2>
    {% if categories %}
        <ul>
        {% for category in categories %}
            <li><a href="{% url 'blog:category' category.id %}">{{ category.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts.</p>
    {% endif %}

    <h2>Posts</h2>
    {% if posts %}
        <ul>
        {% for post in posts %}
            <li><a href="{% url 'blog:post' post.id %}">{{ post.title }}</a></li>{{ post.get_absolute_url }}
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts.</p>
    {% endif %}

{% endblock %}

blog/templates/blog/view_category.html
{% extends 'blog/base.html' %} 
{% block head_title %}Viewing category {{ category.title }}{% endblock %}
{% block title %}{{ category.title }}{% endblock %}

{% block content %}
    {% if posts %}
        <ul>
        {% for post in posts %}
            <li><a href="{% url 'blog:post' post.id %}">{{ post.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/view_post.html
{% extends 'blog/base.html' %} 
{% block head_title %}{{ post.title }}{% endblock %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    {{ post.body }}
{% endblock %}